### ISSUE TITLE
stderr: ERROR: Could not find a version that satisfies the requirement ftfy (from clip) (from versions: none)

### ISSUE THREAD

**Issue by luckydevil13** [HardAndHeavy/stable-diffusion-webui-rocm-docker#2]
` make run
if [ ! -f "/home/andy/stable-diffusion-webui-rocm-docker/data/miniconda_sd_v2.3.0/conda-check-seed-file" ]; then \
        docker run -it --rm \
                -v /home/andy/stable-diffusion-webui-rocm-docker/data/miniconda_sd_v2.3.0:/opt/miniconda_seed \
                hardandheavy/stable-diffusion-webui-rocm:latest sh -c \
                        "cp -r /opt/miniconda/* /opt/miniconda_seed && \
                        touch /opt/miniconda_seed/conda-check-seed-file"; fi
docker run -it --rm \
        -p 80:80 \
        --device=/dev/kfd \
        --device=/dev/dri \
        --ipc=host \
        --cap-add=SYS_PTRACE \
        --security-opt seccomp=unconfined \
        -e HSA_OVERRIDE_GFX_VERSION=11.0.0 \
        -v ./data/check:/check \
        -v ./data/home:/root \
        -v /home/andy/stable-diffusion-webui-rocm-docker/data/miniconda_sd_v2.3.0:/opt/miniconda \
        -v ./data/stable-diffusion:/stable-diffusion \
        -v ./data/sd-webui:/sd-webui \
        hardandheavy/stable-diffusion-webui-rocm:latest
if [ ! -f /check/check-seed-file ]; then \
        git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /sd-webui && \
        pip install insightface && \
        touch /check/check-seed-file; fi
cd /sd-webui && \
python launch.py \
        --no-half \
        --precision=full \
        --port 80 \
        --listen \
        --enable-insecure-extension-access \
        --data-dir=/stable-diffusion
Python 3.11.10 (main, Oct  3 2024, 07:29:13) [GCC 11.2.0]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Installing clip
Traceback (most recent call last):
  File "/sd-webui/launch.py", line 48, in <module>
    main()
  File "/sd-webui/launch.py", line 39, in main
    prepare_environment()
  File "/sd-webui/modules/launch_utils.py", line 394, in prepare_environment
    run_pip(f"install {clip_package}", "clip")
  File "/sd-webui/modules/launch_utils.py", line 144, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sd-webui/modules/launch_utils.py", line 116, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install clip.
Command: "/opt/miniconda/bin/python" -m pip install https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip --prefer-binary --index-url https://download.pytorch.org/whl/rocm6.2
Error code: 1
stdout: Looking in indexes: https://download.pytorch.org/whl/rocm6.2
Collecting https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip
  Using cached https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip (4.3 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
INFO: pip is looking at multiple versions of clip to determine which version is compatible with other requirements. This could take a while.

stderr: ERROR: Could not find a version that satisfies the requirement ftfy (from clip) (from versions: none)
ERROR: No matching distribution found for ftfy

make: *** [Makefile:10: run] Error 1
make: *** [Makefile:45: run] Error 2
`

**Comment by HardAndHeavy** [comment]
Get the current changes. Yes, this error is related to the changes in version 1.10.0. Bypassed by setting the [index variable](https://github.com/HardAndHeavy/stable-diffusion-webui-rocm-docker/blob/main/docker/Dockerfile#L7).

**Comment by luckydevil13** [comment]
> Get the current changes. Yes, this error is related to the changes in version 1.10.0. Bypassed by setting the [index variable](https://github.com/HardAndHeavy/stable-diffusion-webui-rocm-docker/blob/main/docker/Dockerfile#L7).

thanks, via env variable works
